### ISSUE TITLE
camelCase notation for files

### ISSUE THREAD

**Issue by Krzysiek102** [AgnieszkaKurek/WordWarI#11]
Files in images and pages directory has names that are not compliant with camelCase notation.

**Comment by Krzysiek102** [comment]
Still several files has not camel case notation.

**Comment by AgnieszkaKurek** [comment]
Done. Names longer than one expressive improved

**Comment by Krzysiek102** [comment]
Pages files are not changed:
https://github.com/AgnieszkaKurek/WordWarI/tree/master/pages

**Comment by Krzysiek102** [comment]
To zdjęcie:
https://github.com/AgnieszkaKurek/WordWarI/blob/master/images/TheGreatWar.jpg
Nie ma jeszcze nazwy w notacji camelCase.

**Comment by Krzysiek102** [comment]
This image:
https://github.com/AgnieszkaKurek/WordWarI/blob/master/images/TheGreatWar.jpg
Still does not have name in camel case notation - I wrote it in my previous comment, but you ignored it.
